### PR TITLE
Update fonts to include correct Helm icon

### LINKED ISSUE #286: Helm icon is not being rendered correctly
I've always wondered that the Helm icon in the Argo CD UI looks a bit strange, but today I decided to go down that rabbit hole and found out that this is actually being rendered by custom icon font. This screenshot is from Edge, but it looks similarly bad on all other browser I had available (Chrome and Firefox):

image

### PR DESCRIPTION
**Pull request by tongpu**
This is a follow-up to #287 in which I updated the Helm icon, but did not update the font files.

Fixes #286

### CODE REVIEW

**Comment by tongpu** [comment]
@saumeya @rbreeze This is a follow-up for my previous PR, because I didn't know how to update the font files. This should now fix the Helm icon in the UI.

**Comment by tongpu** [comment]
@saumeya @rbreeze Would you be able to review this and include the changes?

**Comment by agilgur5** [comment]
Asking @rbreeze over CNCF Slack if he could review this.

Thanks for your efforts in fixing this again!

**Review by rbreeze — APPROVED** [review]
LGTM

**Pull request merged**
