### PR TITLE
fix: Design Flaw leading to errant delete #4844

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

This is the argo-ui part of the fix for https://github.com/argoproj/argo-cd/issues/4844

This 'general' fix improves the prompt window so clients can customize the header colour and icon colour.  Specifically,

- A new warning icon was added (ran `yarn utils:icons`)
- The layout of the popup prompt contents was improved when an icon is shown or not (the footer buttons should align with the main body contents)
- It allows for red, yellow title colours in the prompt window (Clients should put ‘red’ or ‘yellow’ or ‘normal’ values only for now)
- New property/option for title colour and icons have been added and are made optional to not break existing code and behaviour.
- Layout of `<h4>` and `<p>` elements improved.  All components should be aligned left with or without icon. Any custom indentation should be added by clients.
- Added five new storybook items as examples.

Note that the implementation of the icon colour was not changed (The use of `warning`, `success`, and `failed` was left unchanged, to not break existing code and behaviour)

**_Note_** that this change might require clients to modify their horizontal spacing (likely shrink or remove them) so that the components will better align with the footer buttons.

### CODE REVIEW

**Comment by keithchong** [comment]
Screen Shot 2020-11-20 at 3 05 18 PM
Screen Shot 2020-11-20 at 3 05 31 PM
Screen Shot 2020-11-20 at 3 05 51 PM

**Comment by keithchong** [comment]
Hi @alexmt , please review

**Comment by alexmt** [comment]
Thank you for attaching screenshots! It made it really easy to review.

**Review by alexmt — APPROVED** [review]
LGTM

**Pull request merged**
