### PR TITLE
Update Helm icon

### PR DESCRIPTION
**Pull request by tongpu**
As a first follow-up to #286 I looked into the different SVG files and I had the feeling that some with multiple paths are not translated into `argo-icons.svg` correctly.

This is an updated version of the black Helm icon taken from the [CNCF Branding](https://cncf-branding.netlify.app/projects/helm/) page with the paths combined into a single path.

### CODE REVIEW

**Comment by tongpu** [comment]
@saumeya @rbreeze Would you be willing to help me get this sorted out?

**Review by saumeya — APPROVED** [review]
lgtm

**Comment by saumeya** [comment]
closes #286

**Review by rbreeze — APPROVED** [review]

**Comment by tongpu** [comment]
I think the font files in `src/assets/fonts` would also need to be updated, but that was the part that I didn't manage to figure out yet and hoped that you have some tooling which generates the font files from the directories of SVGs.

**Pull request merged**
