### PR TITLE
Support workflow template

### PR DESCRIPTION
**Pull request by dtaniwaki**
I made a support of `WorkflowTemplate`. I changed the format of template YAML view so you can check the source of resolved templates.

I also updated node-sass version to ^4.12.0 because of https://github.com/sass/node-sass/issues/2632.

### CODE REVIEW

**Comment by dtaniwaki** [comment]
Here're screenshots of the steps view with workflow templates.
Screen Shot 2019-12-12 at 9 12 59 PM
Screen Shot 2019-12-12 at 9 13 14 PM
Screen Shot 2019-12-12 at 9 13 19 PM

**Comment by dtaniwaki** [comment]
It also works with DAG templates.
Screen Shot 2019-12-12 at 11 02 18 PM
Screen Shot 2019-12-12 at 11 02 31 PM

**Comment by dtaniwaki** [comment]
The fix of template scope is neccessary to make this fix work with `examples/workflow-template/hello-world.yml` in the argo repo.
https://github.com/argoproj/argo/pull/1836

**Comment by dtaniwaki** [comment]
Please try out `dtaniwaki/argoui:v2.2.1-cfca2f6` from DockerHub.

**Comment by Jude188** [comment]
Any idea when we might see this feature in a release?

**Pull request merged**
