### PR TITLE
refactor: upgrade xterm version

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

PR upgrades xterm version and adapt LogsViewer to new xterm API

Screen Shot 2022-03-21 at 3 52 26 PM

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
Thank you @alexmt code looks good, but when i am linking this version of UI to current argocd I get such error


I
Снимок экрана 2022-03-22 в 17 53 43

is it just for me ?

**Comment by alexmt** [comment]
@pasha-codefresh did you run `yarn install` before testing ?

**Review by pasha-codefresh — APPROVED** [review]

**Comment by chenyuf4** [comment]
There are still issues of argo-ui. When I update this version of argo-ui and I do `yarn test` in Argocd, the following errors comes up. 
Screen Shot 2022-03-29 at 11 49 00 AM

The reason is that xterm/FitAddon uses `self` in its implementation, which refers to the window object. However, the test environment of Argocd is node.js, which has no window object. Could you help to resolve this issue?

**Comment by agilgur5** [comment]
Fixed #180

**Pull request merged**
