### PR TITLE
feat: New components from Argo Rollouts UI in src/v2 directory

### PR DESCRIPTION
**Pull request by rbreeze**
Signed-off-by: Remington Breeze <remington@breeze.software>

### CODE REVIEW

**Review by alexec — COMMENTED** [review]
is there a demo mode for these new ones?

**Comment by rbreeze** [comment]
In a previous PR I made a little live code explorer where you could try them out, but I closed it because I'm not sure I want to maintain a storybook replacement. 

https://github.com/argoproj/argo-ui/pull/98

If you clone this PR and `yarn start` it'll spin up the explorer

**Comment by alexec** [comment]
if it is easy to add screenshots to the PR, that'd be great

**Comment by rbreeze** [comment]
`ActionButton` (normal and hover states): 

Screen Shot 2021-04-29 at 10 28 57 AM
Screen Shot 2021-04-29 at 10 29 06 AM

`ActionButton` dark mode (normal and hover states):

Screen Shot 2021-04-29 at 10 30 00 AM
Screen Shot 2021-04-29 at 10 29 54 AM

`Autocomplete` Field: 

Screen Shot 2021-04-29 at 10 29 36 AM


`InfoItemRow`s:

Screen Shot 2021-04-29 at 10 30 24 AM


`Alert`: 

Screen Shot 2021-04-29 at 10 31 10 AM


`Menu`: 

Screen Shot 2021-04-29 at 10 32 12 AM


`Tooltip`: 

Screen Shot 2021-04-29 at 10 32 28 AM

**Comment by alexec** [comment]
@jessesuen can we get Remington to come and revamp the workflows UI? He's done a great job modernizing. The Argo CD is much more attractive now.

**Comment by rbreeze** [comment]
Note: New components and documentation are visible at https://breeze.software/argo-ui/ (for now until changes are merged, should be available at an Argo Github URL in the future)

**Review by alexmt — APPROVED** [review]

**Pull request merged**
