### PR TITLE
chore: introduce jest for unit testing

### PR DESCRIPTION
**Pull request by dcherman**
This introduces Jest as a framework for unit testing, including some
basic tests for the Checkbox.  The component being tested here is
intentionally minimal since this serves as our PR to set up the infra
for unit testing rather than introducing large amounts of tests.

### CODE REVIEW

**Review by simster7 — COMMENTED** [review]
Overall this LGTM, but I'd also like @alexmt to take a look

**Comment by dcherman** [comment]
@alexmt WDYT?

**Comment by simster7** [comment]
> @alexmt WDYT?

I believe he is off for the rest of this week, but I'll make sure to bring it up to him by Monday. My bad, I should have done this sooner.

**Comment by alexmt** [comment]
Sorry for the delay @dcherman .

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by dcherman** [comment]
Changes have been rebased on top of master.

**Comment by alexmt** [comment]
Thank you!

**Pull request merged**
