### PR TITLE
refactor: upgrade dependencies and node version

### PR DESCRIPTION
**Pull request by alexmt**
PR upgrades libraries versions and node version to 12.18.4 (LTS)

### CODE REVIEW

**Comment by alexec** [comment]
Can I request an upgrade of react-helment too please? I don't seem to be able to do this myself.

**Comment by alexmt** [comment]
Sure, upgraded react-helment as well.

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
If you can trim any dependencies that would be great too :)

**Comment by alexmt** [comment]
Good point! Removed `superagent`, `superagent-promise`, `ws` and `yamljs`.

**Comment by alexec** [comment]
I don't seem to be able to build this PR with workflows, I get these errors:

```
ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/shared/components/input-filter.tsx
./src/app/shared/components/input-filter.tsx
[tsl] ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/shared/components/input-filter.tsx(38,26)
      TS2322: Type '{ onKeyUp: (event: KeyboardEvent<HTMLInputElement>) => void; className: string; placeholder: string; accept?: string; acceptCharset?: string; action?: string; ... 351 more ...; key?: ReactText; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
  Type '{ onKeyUp: (event: KeyboardEvent<HTMLInputElement>) => void; className: string; placeholder: string; accept?: string; acceptCharset?: string; action?: string; ... 351 more ...; key?: ReactText; }' is not assignable to type 'InputHTMLAttributes<HTMLInputElement>'.
    Types of property 'style' are incompatible.
      Type 'import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/node_modules/@types/react/index").CSSProperties' is not assignable to type 'React.CSSProperties'.

ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/shared/components/tags-input/tags-input.tsx
./src/app/shared/components/tags-input/tags-input.tsx
[tsl] ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/shared/components/tags-input/tags-input.tsx(61,26)
      TS2322: Type '{ placeholder: string; ref: (inputEl: HTMLInputElement) => void; onFocus: (e: FocusEvent<HTMLInputElement>) => void; onBlur: (e: FocusEvent<HTMLInputElement>) => void; ... 353 more ...; key?: ReactText; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
  Type '{ placeholder: string; ref: (inputEl: HTMLInputElement) => void; onFocus: (e: FocusEvent<HTMLInputElement>) => void; onBlur: (e: FocusEvent<HTMLInputElement>) => void; ... 353 more ...; key?: ReactText; }' is not assignable to type 'InputHTMLAttributes<HTMLInputElement>'.
    Types of property 'style' are incompatible.
      Type 'import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/node_modules/@types/react/index").CSSProperties' is not assignable to type 'React.CSSProperties'.

ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
./src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
[tsl] ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx(68,37)
      TS2322: Type '() => import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/rxjs/Observable").Observable<string>' is not assignable to type '() => import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/node_modules/rxjs/Observable").Observable<string>'.
  Call signature return types 'Observable<string>' and 'Observable<string>' are incompatible.
    The types of 'source' are incompatible between these types.
      Type 'import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/rxjs/Observable").Observable<any>' is not assignable to type 'import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/node_modules/rxjs/Observable").Observable<any>'.
        Property 'operator' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/workflows/components/workflows-list/workflows-list.tsx
./src/app/workflows/components/workflows-list/workflows-list.tsx
[tsl] ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/workflows/components/workflows-list/workflows-list.tsx(388,34)
      TS2322: Type '{ onFocus: (e: FocusEvent<HTMLInputElement>) => void; className: string; accept?: string; acceptCharset?: string; action?: string; allowFullScreen?: boolean; ... 351 more ...; key?: ReactText; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
  Type '{ onFocus: (e: FocusEvent<HTMLInputElement>) => void; className: string; accept?: string; acceptCharset?: string; action?: string; allowFullScreen?: boolean; ... 351 more ...; key?: ReactText; }' is not assignable to type 'InputHTMLAttributes<HTMLInputElement>'.
    The types of 'style.borderBlockEndStyle' are incompatible between these types.
      Type 'string' is not assignable to type 'BorderBlockEndStyleProperty'.

ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/src/components/data-loader.tsx
./node_modules/argo-ui/src/components/data-loader.tsx
[tsl] ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/src/components/data-loader.tsx(62,30)
      TS2322: Type 'import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/node_modules/@types/react/index").CSSProperties' is not assignable to type 'React.CSSProperties'.
  Types of property 'borderBlockEndStyle' are incompatible.
    Type 'string' is not assignable to type 'BorderBlockEndStyleProperty'.

ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/src/components/data-loader.tsx
./node_modules/argo-ui/src/components/data-loader.tsx
[tsl] ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/src/components/data-loader.tsx(71,80)
      TS2322: Type 'import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/node_modules/@types/react/index").CSSProperties' is not assignable to type 'React.CSSProperties'.

ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/src/components/autocomplete/autocomplete-field.tsx
./node_modules/argo-ui/src/components/autocomplete/autocomplete-field.tsx
[tsl] ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/src/components/autocomplete/autocomplete-field.tsx(25,18)
      TS2322: Type '{ onFocus: (e: FocusEvent<HTMLInputElement>) => void; onBlur: (e: FocusEvent<HTMLInputElement>) => void; accept?: string; ... 354 more ...; key?: ReactText; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
  Type '{ onFocus: (e: FocusEvent<HTMLInputElement>) => void; onBlur: (e: FocusEvent<HTMLInputElement>) => void; accept?: string; ... 354 more ...; key?: ReactText; }' is not assignable to type 'InputHTMLAttributes<HTMLInputElement>'.
    Types of property 'style' are incompatible.
      Type 'import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/node_modules/@types/react/index").CSSProperties' is not assignable to type 'React.CSSProperties'.
```

**Comment by alexmt** [comment]
@alexec I'm working on PR similar to https://github.com/argoproj/argo-cd/pull/4461 for workflows. Will make sure both projects are built successfully before merging it.

**Comment by alexmt** [comment]
Tried to build argo-workflows ui locally. It seems fine. Did not have to make any additional changes. CI is also green: https://github.com/argoproj/argo/pull/4178

**Comment by alexmt** [comment]
@alexec I'm pretty sure workflows UI builds with updated dependencies. Merging changes and updating Argo CD and Argo Workflow PRs

**Pull request merged**
