### PR TITLE
fix: upgrade all dependencies identified by snyk as having vulns

### PR DESCRIPTION
**Pull request by dcherman**
Signed-off-by: Daniel Herman <dherman@factset.com>

### CODE REVIEW

**Comment by alexec** [comment]
Looks good. When I try and add to argo-workflows I get this error:

```
yarn add "https://github.com/dcherman/argo-ui.git#97d2d34"
```

```
...
ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
./src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx
[tsl] ERROR in /Users/acollins8/go/src/github.com/argoproj/argo/ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx(73,37)
      TS2322: Type '() => import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/rxjs/Observable").Observable<string>' is not assignable to type '() => import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/node_modules/rxjs/Observable").Observable<string>'.
  Call signature return types 'Observable<string>' and 'Observable<string>' are incompatible.
    The types of 'source' are incompatible between these types.
      Type 'import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/rxjs/Observable").Observable<any>' is not assignable to type 'import("/Users/acollins8/go/src/github.com/argoproj/argo/ui/node_modules/argo-ui/node_modules/rxjs/Observable").Observable<any>'.
        Property 'operator' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
```

Any suggestions?

**Comment by alexec** [comment]
Passes tests:

```bash
(chore/fix-snyk-vulns) ✗ snyk test

Testing /Users/acollins8/argo-ui...

Organization:      argoproj
Package manager:   yarn
Target file:       yarn.lock
Project name:      argo-ui
Open source:       no
Project path:      /Users/acollins8/argo-ui
Licenses:          enabled

✓ Tested 242 dependencies for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
```

**Comment by dcherman** [comment]
@alexec I think the typings between multiple different versions of RxJS are incompatible, so upgrading RxJS to ^5.5.11 in Argo Workflows should fix that.  I suspect that `RxJS` should actually be a peerDependency in argo-ui to leave the decision about the particular version in use to the app, but haven't looked into that enough to determine if that's a correct assertion.

**Comment by alexec** [comment]
`yarn remove rxjs` works too.

**Review by alexec — APPROVED** [review]

**Pull request merged**
