### PR TITLE
fix(navigation): invalid redirection

### LINKED ISSUE #564: Navigation error with location.href ends with `/`
When I discover applications using `https://argocd.com/service/applications/`, search applications and then click it.
But it is redirected to `https://argocd.com/service/applications//{application-name}`. so the slash in the end has to be removed.

### PR DESCRIPTION
**Pull request by KSH-code**
fix #564

When I discover applications on like `https://argocd.com/service/applications/`, search applications and then click it.
But it is redirected to `https://argocd.com/service/applications//{application-name}`.
And an empty page is shown.

for the soultion, the slash in the end has to be removed.

### CODE REVIEW

**Comment by KSH-code** [comment]
Hi @agilgur5 
Could you please a feedback pr for merging?
Thanks!

**Comment by agilgur5** [comment]
I can take a look, but I'm not a CD Maintainer so I wouldn't merge on my own in any case. It would be good to link to an issue upstream as well per #453

**Comment by KSH-code** [comment]
Thank you for your check.
I've made an issue on https://github.com/argoproj/argo-cd/issues/19093 which include referring this.

**Comment by agilgur5** [comment]
I left a comment on your upstream issue; this is perhaps better addressed upstream than here: https://github.com/argoproj/argo-cd/issues/19093#issuecomment-2240032528

**Comment by KSH-code** [comment]
I agree. I close this so that I will address this issue on upstream.

**Pull request closed without merging**
